#!/bin/bash
# init script for Portal.
# chkconfig: 2345 90 10
# description: Portal

. /etc/init.d/functions

BIN="/usr/local/bin/django-admin.py"
USER="jetty"
PID=/var/lib/portal/portal.pid
LOG=/var/log/portal/portal.out
prog="portal"
HOST="0.0.0.0"
PORT="8080"
SETTINGMODULE="qa300"
RUNCOMMAND="runserver $HOST:$PORT"
SYNCDBCOMMAND="syncdb"
MIGRATECOMMAND="migrate"
SETTINGS="--settings=upgrades.settings.$SETTINGMODULE"

if [ ! -f $BIN ]; then
  echo "File not found: $BIN"
  exit 1
fi

RETVAL=0

start() {
  if [ -f $PID ] && checkpid `cat $PID`; then
    echo "$prog is already running."
    exit 0
  fi
  echo -n $"Starting $prog: "
  daemon --user $USER $BIN $RUNCOMMAND $SETTINGS >> /dev/null 2>&1
  usleep 500000
  RETVAL=$?
  echo
  return $RETVAL
}

syncdb() {
  $BIN $SYNCDBCOMMAND $SETTINGS >> $LOG 2>&1
  usleep 500000
  RETVAL=$?
  echo
  return $RETVAL
}

migrate() {
  $BIN $MIGRATECOMMAND $SETTINGS >> $LOG 2>&1
  usleep 500000
  RETVAL=$?
  echo
  return $RETVAL
}

stop() {
  # check if the process is already stopped by seeing if the pid file exists.
  if [ ! -f $PID ]; then
    echo "$prog is already stopped."
    exit 0
  fi
  echo -n $"Stopping $prog: "
  if kill `cat $PID`; then
    RETVAL=0
    echo_success
  else
    RETVAL=1
    echo_failure
  fi
  echo
  [ $RETVAL = 0 ]
}

status_fn() {
  if [ -f $PID ] && checkpid `cat $PID`; then
    echo "$prog is running."
    exit 0
  else
    echo "$prog is stopped."
    exit 1
  fi
}

case "$1" in
  start)
    start
    ;;
  syncdb)
    syncdb
    ;;
  migrate)
    migrate
    ;;
  stop)
    stop
    ;;
  status)
    status_fn
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status|syncdb|migrate}"
    RETVAL=3
esac

exit $RETVAL
