QA300LISTUM = 'http://ipws-ssota-qa.blurdev.com/upgrade-management/3/upgradepaths/'
QA300GETUM = 'http://ipws-ssota-qa.blurdev.com/upgrade-management/1/upgradepaths/'
QA300PMGETBINARIES = 'http://ipws-ssota-qa.blurdev.com/package-management-1.0/ws/pm/1/binaries'
QA300PMGETPACKAGES = 'http://ipws-ssota-qa.blurdev.com/package-management-1.0/ws/pm/1/packages?submit=true&filter=&columns=name,product,region,carrier,source,language'
QA300DEVICEEVENTS = 'http://otasm-qa300.blurdev.com/upgrade/ws/upgrade/1/devices/events/'
QA300LISTOFELIGIBLEDEVICE =  'http://otasm-qa300.blurdev.com/upgrade/ws/upgrade/1/reports/data/'
QA300TLMSLISTS = 'http://tlms-qa300.blurdev.com/tlms-service/tlms/1/list'
QA300TLMSTARGETS = 'http://tlms-qa300.blurdev.com/tlms-service/tlms/1/target'
QA300TLMSMATCH = 'http://tlms-qa300.blurdev.com/tlms-service/tlms/1/matcher/defaulter'
QA300TLMSCHECK = 'http://tlms-qa300.blurdev.com/tlms-service/tlms/1/matcher'
QA300STATS = 'http://otasm-qa300.blurdev.com/upgrade/ws/upgrade/1/stats'
QA300TIMELINE = 'http://otasm-qa300.blurdev.com/upgrade/ws/upgrade/1/timeline'
QA300OSMSUPS = 'http://otasm-qa300.blurdev.com/upgrade/ws/upgrade/1/upgradepaths/' # Append the SUP GUID 5f9b0db4-c279-491d-9d71-33d61782f450


SDC200LISTUM = 'http://ipws-ssota-sdc200.blurdev.com/upgrade-management/3/upgradepaths/'
SDC200GETUM = 'http://ipws-ssota-sdc200.blurdev.com/upgrade-management/1/upgradepaths/'
SDC200PMGETBINARIES = 'http://ipws-ssota-sdc200.blurdev.com/package-management-1.0/ws/pm/1/binaries'
SDC200PMGETPACKAGES = 'http://ipws-ssota-sdc200.blurdev.com/package-management-1.0/ws/pm/1/packages?submit=true&filter=&columns=name,product,region,carrier,source,language'
SDC200DEVICEEVENTS = 'http://otasm-sdc200.blurdev.com/upgrade/ws/upgrade/1/devices/events/'
SDC200LISTOFELIGIBLEDEVICE =  'http://otasm-sdc200.blurdev.com/upgrade/ws/upgrade/1/reports/data/'
SDC200TLMSLISTS = 'http://tlms-sdc200.blurdev.com/tlms-service/tlms/1/list'
SDC200TLMSTARGETS = 'http://tlms-sdc200.blurdev.com/tlms-service/tlms/1/target'
SDC200TLMSMATCH = 'http://tlms-sdc200.blurdev.com/tlms-service/tlms/1/matcher/defaulter'
SDC200TLMSCHECK = 'http://tlms-sdc200.blurdev.com/tlms-service/tlms/1/matcher'
SDC200STATS = 'http://otasm-sdc200.blurdev.com/upgrade/ws/upgrade/1/stats'
SDC200TIMELINE = 'http://otasm-sdc200.blurdev.com/upgrade/ws/upgrade/1/timeline'
SDC200OSMSUPS = 'http://otasm-sdc200.blurdev.com/upgrade/ws/upgrade/1/upgradepaths/' # Append the SUP GUID 5f9b0db4-c279-491d-9d71-33d61782f450

SDC100LISTUM = 'http://ipws-ssota-sdc.blurdev.com/upgrade-management/2/upgradepaths/'
SDC100GETUM = 'http://ipws-ssota-sdc.blurdev.com/upgrade-management/1/upgradepaths/'
SDC100PMGETBINARIES = 'http://ipws-ssota-sdc.blurdev.com/package-management-1.0/ws/pm/1/binaries'
SDC100PMGETPACKAGES = 'http://ipws-ssota-sdc.blurdev.com/package-management-1.0/ws/pm/1/packages?submit=true&filter=&columns=name,product,region,carrier,source,language'
SDC100DEVICEEVENTS = 'http://otasm-sdc100.blurdev.com/upgrade/ws/upgrade/1/devices/events/'
SDC100LISTOFELIGIBLEDEVICE =  'http://otasm-sdc100.blurdev.com/upgrade/ws/upgrade/1/reports/data/'
SDC100TLMSLISTS = 'http://tlms-sdc100.blurdev.com/tlms-service/tlms/1/list'
SDC100TLMSTARGETS = 'http://tlms-sdc100.blurdev.com/tlms-service/tlms/1/target'
SDC100TLMSMATCH = 'http://tlms-sdc100.blurdev.com/tlms-service/tlms/1/matcher/defaulter'
SDC100TLMSCHECK = 'http://tlms-sdc100.blurdev.com/tlms-service/tlms/1/matcher'
SDC100STATS = 'http://otasm-sdc100.blurdev.com/upgrade/ws/upgrade/1/stats'
SDC100TIMELINE = 'http://otasm-sdc100.blurdev.com/upgrade/ws/upgrade/1/timeline'
SDC100OSMSUPS = 'http://otasm-sdc100.blurdev.com/upgrade/ws/upgrade/1/upgradepaths/' # Append the SUP GUID 5f9b0db4-c279-491d-9d71-33d61782f450

GCELISTUM = 'http://173.255.113.44:8080/upgrade-management/2/upgradepaths/'
GCEGETUM = 'http://173.255.113.44:8080/upgrade-management/1/upgradepaths/'
GCEPMGETBINARIES = 'http://173.255.113.44:8080/package-management-1.0/ws/pm/1/binaries'
GCEPMGETPACKAGES = 'http://173.255.113.44:8080/package-management-1.0/ws/pm/1/packages?submit=true&filter=&columns=name,product,region,carrier,source,language'
GCEDEVICEEVENTS = 'http://108.59.80.138:8080/upgrade/ws/upgrade/1/devices/events/'
GCELISTOFELIGIBLEDEVICE =  'http://108.59.80.138:8080/upgrade/ws/upgrade/1/reports/data/'
GCETLMSLISTS = 'http://173.255.119.157:8080/tlms-service/tlms/1/list'
GCETLMSTARGETS = 'http://173.255.119.157:8080/tlms-service/tlms/1/target'
GCETLMSMATCH = 'http://173.255.119.157:8080/tlms-service/tlms/1/matcher/defaulter'
GCETLMSCHECK = 'http://173.255.119.157:8080/tlms-service/tlms/1/matcher'
GCESTATS = 'http://108.59.80.138:8080/upgrade/ws/upgrade/1/stats'
GCETIMELINE = 'http://108.59.80.138:8080/upgrade/ws/upgrade/1/timeline'

PRODLISTUM = 'http://ipws-ssota.gtm.svcmot.com/upgrade-management/2/upgradepaths/'
PRODGETUM = 'http://ipws-ssota.gtm.svcmot.com/upgrade-management/1/upgradepaths/'
PRODPMGETBINARIES = 'http://ipws-ssota.gtm.svcmot.com/package-management-1.0/ws/pm/1/binaries'
PRODPMGETPACKAGES = 'http://ipws-ssota.gtm.svcmot.com/package-management-1.0/ws/pm/1/packages?submit=true&filter=&columns=name,product,region,carrier,source,language'
PRODDEVICEEVENTS = 'http://otasm.gtm.svcmot.com/upgrade/ws/upgrade/1/devices/events/'
PRODLISTOFELIGIBLEDEVICE =  'http://otasm.gtm.svcmot.com/upgrade/ws/upgrade/1/reports/data/'
PRODTLMSLISTS = 'http://tlms.gtm.svcmot.com/tlms-service/tlms/1/list'
PRODTLMSTARGETS = 'http://tlms.gtm.svcmot.com/tlms-service/tlms/1/target'
PRODTLMSMATCH = 'http://tlms.gtm.svcmot.com/tlms-service/tlms/1/matcher/defaulter'
PRODTLMSCHECK = 'http://tlms.gtm.svcmot.com/tlms-service/tlms/1/matcher'
PRODSTATS = 'http://otasm.gtm.svcmot.com/upgrade/ws/upgrade/1/stats'
PRODTIMELINE = 'http://otasm.gtm.svcmot.com/upgrade/ws/upgrade/1/timeline'
PRODOSMSUPS = 'http://otasm.gtm.svcmot.com/upgrade/ws/upgrade/1/upgradepaths/' # Append the SUP GUID 5f9b0db4-c279-491d-9d71-33d61782f450

# @TODO: Point to ILC hosts after they have been deployed
PRODILC_LISTUM = 'http://ipws-ssota.gtm.svcmot.com/upgrade-management/2/upgradepaths/'
PRODILC_GETUM = 'http://ipws-ssota.gtm.svcmot.com/upgrade-management/1/upgradepaths/'
PRODILC_PMGETBINARIES = 'http://ipws-ssota.gtm.svcmot.com/package-management-1.0/ws/pm/1/binaries'
PRODILC_PMGETPACKAGES = 'http://ipws-ssota.gtm.svcmot.com/package-management-1.0/ws/pm/1/packages?submit=true&filter=&columns=name,PRODILC_uct,region,carrier,source,language'
PRODILC_DEVICEEVENTS = 'http://otasm.gtm.svcmot.com/upgrade/ws/upgrade/1/devices/events/'
PRODILC_LISTOFELIGIBLEDEVICE =  'http://otasm.gtm.svcmot.com/upgrade/ws/upgrade/1/reports/data/'
PRODILC_TLMSLISTS = 'http://tlms.gtm.svcmot.com/tlms-service/tlms/1/list'
PRODILC_TLMSTARGETS = 'http://tlms.gtm.svcmot.com/tlms-service/tlms/1/target'
PRODILC_TLMSMATCH = 'http://tlms.gtm.svcmot.com/tlms-service/tlms/1/matcher/defaulter'
PRODILC_TLMSCHECK = 'http://tlms.gtm.svcmot.com/tlms-service/tlms/1/matcher'
PRODILC_STATS = 'http://otasm.gtm.svcmot.com/upgrade/ws/upgrade/1/stats'
PRODILC_TIMELINE = 'http://otasm.gtm.svcmot.com/upgrade/ws/upgrade/1/timeline'
PRODILC_OSMSUPS = 'http://otasm.gtm.svcmot.com/upgrade/ws/upgrade/1/upgradepaths/' # Append the SUP GUID 5f9b0db4-c279-491d-9d71-33d61782f450

PRODVA3_LISTUM = 'http://ipws-ssota-va3.svcmot.com/upgrade-management/2/upgradepaths/'
PRODVA3_GETUM = 'http://ipws-ssota-va3.svcmot.com/upgrade-management/1/upgradepaths/'
PRODVA3_PMGETBINARIES = 'http://ipws-ssota-va3.svcmot.com/package-management-1.0/ws/pm/1/binaries'
PRODVA3_PMGETPACKAGES = 'http://ipws-ssota-va3.svcmot.com/package-management-1.0/ws/pm/1/packages?submit=true&filter=&columns=name,product,region,carrier,source,language'
PRODVA3_DEVICEEVENTS = 'http://otasm-va3.svcmot.com/upgrade/ws/upgrade/1/devices/events/'
PRODVA3_LISTOFELIGIBLEDEVICE =  'http://otasm-va3.svcmot.com/upgrade/ws/upgrade/1/reports/data/'
PRODVA3_TLMSLISTS = 'http://tlms-va3.svcmot.com/tlms-service/tlms/1/list'
PRODVA3_TLMSTARGETS = 'http://tlms-va3.svcmot.com/tlms-service/tlms/1/target'
PRODVA3_TLMSMATCH = 'http://tlms-va3.svcmot.com/tlms-service/tlms/1/matcher/defaulter'
PRODVA3_TLMSCHECK = 'http://tlms-va3.svcmot.com/tlms-service/tlms/1/matcher'
PRODVA3_STATS = 'http://otasm-va3.svcmot.com/upgrade/ws/upgrade/1/stats'
PRODVA3_TIMELINE = 'http://otasm-va3.svcmot.com/upgrade/ws/upgrade/1/timeline'
PRODVA3_OSMSUPS = 'http://otasm-va3.svcmot.com/upgrade/ws/upgrade/1/upgradepaths/' # Append the SUP GUID 5f9b0db4-c279-491d-9d71-33d61782f450

GAEDEVICEEVENTS = 'https://moto-cds.appspot.com/cds/upgrade/1/devices/events/'
GAELISTOFELIGIBLEDEVICE =  'http://moto-cds.appspot.com/cds/upgrade/ws/upgrade/1/reports/data/'
GAEGETUM = 'https://moto-cds.appspot.com/cds/upgrade/1/deploymentplans/'
GAETLMSLISTS = 'https://1.tlms-service.appspot.com/tlms-service/tlms/1/list'
GAETLMSTARGETS = 'https://1.tlms-service.appspot.com/tlms-service/tlms/1/target'
GAETLMSMATCH = 'https://1.tlms-service.appspot.com//tlms-service/tlms/1/matcher/defaulter'
GAETLMSCHECK = 'https://1.tlms-service.appspot.com//tlms-service/tlms/1/matcher'
GAEOSMSUPS = 'https://moto-cds.appspot.com/cds/upgrade/1/deploymentplans/' # Append the SUP GUID 5f9b0db4-c279-491d-9d71-33d61782f450
